config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :reminders
  match ':controller/:action/:id',via: [:get ,:post]
  #get 'reminders/send'

  #post 'reminders/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
	
end

app/models/reminder.rb
class Reminder < ApplicationRecord
  acts_as_birthday :date_of_birth
	validates_presence_of :name
 	validate :user_must_have_been_born
  validates_date :date_of_birth,:on => :create, :on => :today
  # validates_date :date_of_birth
  #validate :birthday
 def self.automatic
  reminder = Reminder.where("extract(month from date_of_birth) = ? AND extract(day from date_of_birth) = ?", Date.today.strftime('%m'), Date.today.strftime('%d'))

    reminder.each do |reminder|
      UserMailer.delay.welcome_email(reminder)
    end
  end 

 #def birthday

  #reminder = Reminder.all.where(:date_of_birth => Date.current)
 
#end
#def birthday_today?
#date_of_birth.month == Time.now.month &&  
#date_of_birth.day == Time.now.day
  
#end
  	def next_birthday
    Date.distance_to(self.date_of_birth)
  	end

  
  	def is_birthday?
  	self.next_birthday[:months] == 0 and self.next_birthday[:days] == 0
 end
  	def user_must_have_been_born
    	if date_of_birth and date_of_birth > Date.today
      errors.add(:date_of_birth, "User must have been born.")
  end
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:name, :email, :date_of_birth)
    end
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder, only: [:show, :edit, :update, :destroy]

  # GET /reminders
  # GET /reminders.json
  def index
    @reminders = Reminder.all

    #@bday = Reminder.find(:conditions => ["DAY(date_of_birth) = ? AND MONTH(date_of_birth) = ?", Date.today.day, Date.today.month])
    #@show = Reminder.find_by(params[:reminder_id]).birthday_today?
  end

  # GET /reminders/1
  # GET /reminders/1.json
  def show
    
  end

  # GET /reminders/new
  def new
    @reminder = Reminder.new
  end

  # GET /reminders/1/edit
  def edit
  end

  # POST /reminders
  # POST /reminders.json
  def create
    @reminder = Reminder.new(reminder_params)

    respond_to do |format|
     
        
        
         #@reminders.each do |reminder|
         if @reminder.save
    
        format.html { redirect_to @reminder, notice: 'Reminder was successfully created.' }
        format.json { render :show, status: :created, location: @reminder }
      else
        format.html { redirect_to new_reminder_path }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    
    end
  
  end

  # PATCH/PUT /reminders/1
  # PATCH/PUT /reminders/1.json
  def update
    respond_to do |format|
      if @reminder.update(reminder_params)
          
        format.html { redirect_to @reminder, notice: 'Reminder was successfully updated.' }
        format.json { render :show, status: :ok, location: @reminder }
      else
        format.html { render :edit }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reminders/1
  # DELETE /reminders/1.json
  def destroy
    @reminder.destroy
    respond_to do |format|
      format.html { redirect_to reminders_url, notice: 'Reminder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
def add

 @reminder = Reminder.find(params[:id])
 if @reminder.date_of_birth.strftime('%d-%m') == Date.today.strftime('%d-%m')
    UserMailer.welcome_email(@reminder).deliver
  redirect_to @reminder, notice: 'Email was successfully sent.'
   end
 
 end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reminder
      @reminder = Reminder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reminder_params
      params.require(:reminder).permit(:name, :email, :date_of_birth)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
	
end

app/views/invoices/_form.html.erb
<%= form_for(invoice) do |f| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :date_of_birth %>
    <%= f.date_select :date_of_birth %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invoices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Date of birth</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.name %></td>
        <td><%= invoice.email %></td>
        <td><%= invoice.date_of_birth %></td>
        <td><%= link_to 'Show', invoice %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @invoice.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @invoice.email %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @invoice.date_of_birth %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Birthday</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reminders/_form.html.erb
<%= form_for(reminder) do |f| %>
  <% if reminder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reminder.errors.count, "error") %> prohibited this reminder from being saved:</h2>

      <ul>
      <% reminder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :date_of_birth %>
   <%= f.date_select :date_of_birth, :class => 'field', :start_year => 1960, :end_year => Time.now.year %>  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reminders/add.html.erb
<%= image_tag ('images')  %>

app/views/reminders/edit.html.erb
<h1>Editing Reminder</h1>

<%= render 'form', reminder: @reminder %>

<%= link_to 'Show', @reminder %> |
<%= link_to 'Back', reminders_path %>

app/views/reminders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reminders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Date of birth</th>
      <th colspan="3"></th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @reminders.each do |reminder| %>
      
            

        <tr>
       <% if reminder.date_of_birth.strftime('%d-%m') == Date.today.strftime('%d-%m') %>
        <td><%= reminder.name %></td>
        <td><%= reminder.email %></td>

        <td>today is <%= reminder.name %>'s birthday</td>
        <td><%= link_to 'Send',{:controller => "reminders", :action => "add", :id => reminder} %></td>

         
       
        
        <td><%= link_to 'Show', reminder %></td>
        <td><%= link_to 'Edit', edit_reminder_path(reminder) %></td>
        <td><%= link_to 'Destroy', reminder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
     <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reminder', new_reminder_path %>

app/views/reminders/new.html.erb
<h1>New Reminder</h1>

<%= render 'form', reminder: @reminder %>

<%= link_to 'Back', reminders_path %>

app/views/reminders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reminder.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @reminder.email %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @reminder.date_of_birth %>
</p>

<%= link_to 'Back', reminders_path %>